import { createClient } from '@/lib/supabase/server';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { CopyTranscriptButton } from '@/components/share/copy-transcript-button';

function formatTime(seconds: number) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
}

export default async function PublicTranscriptPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();
  
  const { data: project } = await supabase
    .from('projects')
    .select('id, title, status, created_at, language')
    .eq('id', id)
    .eq('status', 'ready')
    .single();
  
  if (!project) notFound();
  
  const { data: transcription } = await supabase
    .from('transcriptions')
    .select('segments, language')
    .eq('project_id', id)
    .single();
  
  if (!transcription) notFound();
  
  const segments = transcription.segments as Array<{ id: number; start: number; end: number; text: string }>;
  const fullText = segments.map(s => s.text.trim()).join(' ');
  
  return (
    <main className="min-h-screen bg-[#09090b] text-zinc-100 antialiased font-sans">
      <header className="border-b border-zinc-800/80 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md bg-zinc-100 flex items-center justify-center">
              <span className="text-[#09090b] font-bold text-xs">V</span>
            </div>
            <span className="font-semibold text-sm text-zinc-300">Vidyut Studio</span>
          </Link>
          <span className="text-xs text-zinc-500">Public Transcript</span>
        </div>
      </header>
      
      <div className="max-w-3xl mx-auto px-6 py-12">
        <div className="mb-8">
          <span className="text-[11px] uppercase tracking-wider text-zinc-500 font-mono">Transcript</span>
          <h1 className="text-2xl font-semibold tracking-tight text-zinc-100 mt-1">{project.title || 'Untitled Project'}</h1>
          <div className="flex items-center gap-3 mt-2 text-xs text-zinc-500">
            <span>{new Date(project.created_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</span>
            {transcription.language && <span className="uppercase px-2 py-0.5 bg-zinc-800 rounded font-mono">{transcription.language}</span>}
            <span>{segments.length} segments</span>
          </div>
        </div>
        
        {/* Copy full text button */}
        <CopyTranscriptButton text={fullText} />
        
        {/* Segment viewer */}
        <div className="mt-8 space-y-1">
          {segments.map((seg, i) => (
            <div key={i} className="flex gap-4 py-2.5 border-b border-zinc-800/50 hover:bg-zinc-900/30 px-2 rounded-lg transition-colors">
              <span className="text-xs font-mono text-zinc-600 w-12 shrink-0 pt-0.5">{formatTime(seg.start)}</span>
              <p className="text-sm text-zinc-300 leading-relaxed">{seg.text}</p>
            </div>
          ))}
        </div>
        
        <div className="mt-12 pt-6 border-t border-zinc-800/60 text-center">
          <p className="text-xs text-zinc-600">Generated by <Link href="/" className="text-zinc-400 hover:text-zinc-200">Vidyut Studio</Link></p>
        </div>
      </div>
    </main>
  );
}
