import subprocess
from dotenv import dotenv_values

config = dotenv_values(".env.local")

print("=== SYNCING ALL ENV VARIABLES TO VERCEL ===")
for k, v in config.items():
    if not v:
        continue
    # Exclude VERCEL_OIDC_TOKEN since it is generated by Vercel dynamically
    if k == "VERCEL_OIDC_TOKEN":
        continue
    print(f"Adding {k}...")
    cmd = f'npx vercel env add "{k}" "production,preview" --value "{v}" --yes --force'
    res = subprocess.run(cmd, capture_output=True, text=True, shell=True)
    if res.returncode == 0:
        print(f"  - {k}: SUCCESS")
    else:
        print(f"  - {k}: FAILED")
        print(res.stdout)
        print(res.stderr)
print("=== SYNCING COMPLETED ===")
